backend/models/Queue.php
<?php

/**
 * This is the model class for table "queue".
 *
 * The followings are the available columns in table 'queue':
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $active
 *
 * @property QueueProvider[] $positions\
 * @property QueueProvider $activeProvider
 *
 */
class Queue extends CActiveRecord {
    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'queue';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('name', 'required'),
            array('active', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 50),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, name, description, active', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'providers' => array(self::HAS_MANY, 'QueueProvider', 'queue_id', 'index' => 'position'),
            'positions' => array(self::HAS_MANY, 'QueueProvider', 'queue_id', 'index' => 'position'),
            'activeProvider' => array(self::BELONGS_TO, 'QueueProvider', 'active',)
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'name' => 'Название',
            'description' => 'Описание',
            'active' => 'Активный провайдер',
            'activeProvider.name' => 'Активный провайдер',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('active', $this->active);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     *
     * @param string $className active record class name.
     *
     * @return Queue the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public static function getOptionList()
    {
        return
            array('' => 'Default')
            + TbHtml::listData(static::model()->findAll(), 'id', 'name');
    }

    /**
     * @param QueueProvider $p
     *
     * @return bool
     */
    public function toggleTo(QueueProvider $p)
    {
        $providerMark = $this->activeProvider->provider->alias;
        NetworkHelper::removeConnectionsForProvider($providerMark);

        $result = NetworkHelper::manyToList($p->provider->alias, $this->getAddresses());

        if ( $result )
        {
            if ( $this->getDbConnection()
                ->createCommand("update queue set active=:active where id = :id")
                ->execute(array(':active' => $p->id, ':id' => $this->id)) )
            {
                $this->active = $p->id;
                if( $dns = DnsSettings::model()->findAllByAttributes(array('queue_id' => $this->id, 'auto_dns' => 1)) ) {
                    foreach($dns as $domain) {
                        DnsHelper::markToChangeIp($domain, $p->provider->ext_ip);
                    }
                }
            }
            else
            {
                $result = false;
            }
        }

        $message = ( $result )
            ? "\r\n Q#{$this->id} '{$this->name}' toggled to #{$p->id}:{$p->provider_id} '{$p->provider->name}' \r\n"
            : "\r\n Error on change active queue provider. Q#{$this->id} '{$this->name}' toggled to #{$p->id}:{$p->provider_id} '{$p->provider->name}' \r\n";

        $title = ( $result )
            ? 'Переключение провайдера в очереди ' . $this->name
            : 'Неудачная попытка переключения провайдера в очереди ' . $this->name;

        Event::storeWatchdogMessage($title, $message, ($result) ? Event::TYPE_INTERNET : Event::TYPE_PROGRAM_ERROR);

        return $result;
    }


    /**
     * @param array $cache
     *
     * @return null|QueueProvider
     */
    public function getBestProvider($cache = array())
    {
        if ( !$cache )
        {
            foreach ( $this->positions as $position )
            {
                $cache[$position->provider_id] = $position->provider;
            }
        }
        $positions = $this->positions;

        $get = function ($status) use ($cache, $positions)
        {
            foreach ( $positions as $p )
            {
                if ( !empty( $cache[$p->provider_id] )
                    && $cache[$p->provider_id]->getStatus() == $status
                )
                {
                    return $p;
                }
            }

            return null;
        };

        foreach ( array(
                      NetworkStatus::BEST,
                      NetworkStatus::FINE,
                      NetworkStatus::GOOD,
                      NetworkStatus::POOR
                  ) as $status )
        {
            if ( $p = $get($status) )
            {
                return $p;
            }
        }

        return null;
    }


    public function getDevices()
    {
        return Device::model()
            ->with('group')
            ->findAll("t.queue_id = {$this->id} OR ((t.queue_id IS NULL) AND group.queue_id = {$this->id})");
    }

    public function getAddresses()
    {
        $devices = array();
        foreach ( $this->getDevices() as $d )
        {
            $devices[] = $d->ip;
        }

        return $devices;
    }
}

backend/controllers/QueueController.php
<?php

class QueueController extends Controller
{
	public $modelName='Queue';

    public function accessRules()
    {
        return CMap::mergeArray(
            array(
                array('allow',  // allow all users to perform 'index' and 'view' actions
                    'actions'=>array('getList'),
                    'users'=>array('@'),
                ),
                array('allow',  // allow all users to perform 'index' and 'view' actions
                    'actions'=>array('addProvider', 'sort'),
                    'roles'=>array('admin'),
                ),
            ),
            parent::accessRules()
        );
    }

    protected function getAfterCreateRedirect($model) {
        return array('update','id'=>$model->id);
    }

    protected function getAfterUpdateRedirect($model) {
        return array('update','id'=>$model->id);
    }

    public function actionGetList($id)
    {
        $data = TbHtml::listData(
            Provider::model()->findAll("id NOT IN(SELECT provider_id FROM queue_provider WHERE queue_id = {$id})"),
            'id', 'name');

        foreach( $data as $v => $name)
        {
            echo CHtml::tag('option', array('value' => $v), CHtml::encode($name), true);
        }
    }

    public function actionAddProvider($id)
    {
        $provider = new QueueProvider('insert');
        $provider->queue_id = $id;
        $provider->provider_id = (int)$_POST['provider'];

        if($provider->save()) {
            $this->afterSave($provider);
        } else {
            var_dump($provider->getErrors());
        }

        return Yii::app()->end();
    }

    public function afterSave($model) {
        NetworkHelper::providerWorkerRestart();
    }


    public function actionSort()
    {
        if (isset($_POST['items']) && is_array($_POST['items'])) {
            $i = 1;
            foreach ($_POST['items'] as $item) {
                $provider = QueueProvider::model()->findByPk($item);
                $provider->position = $i;
                if(!$provider->save()) {
                    var_dump($provider->getErrors());
                }
                $i++;
            }
            $this->afterSave($provider);
        }

        return Yii::app()->end();
    }
}

backend/views/queue/_form.php
<?php
/* @var $this QueueController */
/* @var $model Queue */
/* @var $form TbActiveForm */
?>

<div class="well">

    <?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'queue-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
    )); ?>

    <?php echo $form->errorSummary($model); ?>

    <?php echo $form->textFieldControlGroup($model, 'name', array('span' => 5, 'maxlength' => 50)); ?>

    <?php echo $form->textAreaControlGroup($model, 'description', array('rows' => 6, 'span' => 8)); ?>

    <?php // echo $form->textFieldControlGroup($model,'active',array('span'=>5)); ?>

    <div class="control-group">
        <label class="control-label" for="">Провайдеры</label>
        <div class="controls">
            <?php

            $provider = new QueueProvider('search');
            $provider->unsetAttributes();
            $provider->queue_id = ($model->getIsNewRecord()) ? -1 : $model->id;


            $this->widget('SimplePGridView',array(
                'id'=>'queue-provider-grid',
                'dataProvider'=>$provider->search(),
                'htmlOptions' => array('class' => 'margin span8'),
                'afterAjaxUpdate' => 'js: function(){ installSortable(); }',
                'rowCssClassExpression'=>'"items[]_{$data->id}"',
                'hideHeader' => true,
                'addButton' => array(
                    'url' => $this->createUrl('addProvider', array('id' => $model->id)),
                    'icon' => 'plus',
                    'htmlOptions' => array(
                        'class' => 'btn pull-right btn-success ',
                        'id' => 'add-provider',
                        'data-toggle' => 'modal',
                        'data-target' => '#addProviderDialog'
                    )
                ),

                'widgetHeader'=>'Провайдеры',
                'columns'=>array(
                    // 'id',
                    array(
                        'name' => 'provider.name',
                        'htmlOptions' => array('style' => 'width: 50%')

                    ),
                    'position',
//                    array(
//                        'class'=>'PButtonColumn',
//                    ),
                ),
            )); ?>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="form-actions">
        <?php echo TbHtml::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить', array(
            'color' => TbHtml::BUTTON_COLOR_PRIMARY,
            'size' => TbHtml::BUTTON_SIZE_LARGE,
        )); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

<?php $this->widget('bootstrap.widgets.TbModal', array(
    'id' => 'addProviderDialog',
    'header' => 'Добавить провайдера',
    'content' => TbHtml::dropDownList('provider_id', null, array()),
    'onShow' => 'js: function() { $("#provider_id").load("/queue/getList/' . $model->id . '") }',
    'footer' => array(
        TbHtml::button(
            'Добавить',
            array(
                //'data-dismiss' => 'modal',
                'color' => TbHtml::BUTTON_COLOR_PRIMARY,
                'onClick' => 'saveProvider()'
            )
        ),
        TbHtml::button('Отмена', array('data-dismiss' => 'modal')),
    ),
)); ?>

<?php
$str_js = "
        var fixHelper = function(e, ui) {
            ui.children().each(function() {
                $(this).width($(this).width());
            });
            return ui;
        };

        function installSortable(){

            $('#queue-provider-grid table.items tbody').sortable({
                forcePlaceholderSize: true,
                forceHelperSize: true,
                items: 'tr',
                update : function () {
                    serial = $('#queue-provider-grid table.items tbody').sortable('serialize', {key: 'items[]', attribute: 'class'});
                    $.ajax({
                        'url': '" . $this->createUrl('/queue/sort') . "',
                        'type': 'post',
                        'data': serial,
                        'success': function(data){
                            $('#queue-provider-grid').yiiGridView('update');
                        },
                        'error': function(request, status, error){
                           console.log(error);
                        }
                    });
                },
                helper: fixHelper
            }).disableSelection();
        }

        installSortable();
    ";

Yii::app()->clientScript->registerScript('sortable-provider', $str_js);
?>


<script>
    function saveProvider(){

        $.post(
            '/queue/addProvider/<?= $model->id ?>',
            {
                "provider" : $("#provider_id").val()
            },
            function(){
                $("#queue-provider-grid").yiiGridView("update");
            }
        );
        console.log("ok");
        $("#addProviderDialog").modal("hide");
    }
</script>

backend/views/queue/_search.php
<?php
/* @var $this QueueController */
/* @var $model Queue */
/* @var $form CActiveForm */
?>

<div class="wide form">

    <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

                    <?php echo $form->textFieldControlGroup($model,'id',array('span'=>5)); ?>

                    <?php echo $form->textFieldControlGroup($model,'name',array('span'=>5,'maxlength'=>50)); ?>

                    <?php echo $form->textAreaControlGroup($model,'description',array('rows'=>6,'span'=>8)); ?>

                    <?php echo $form->textFieldControlGroup($model,'active',array('span'=>5)); ?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton('Search',  array('color' => TbHtml::BUTTON_COLOR_PRIMARY,));?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- search-form -->

backend/views/queue/_view.php
<?php
/* @var $this QueueController */
/* @var $data Queue */
?>

<div class="view">

    	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('active')); ?>:</b>
	<?php echo CHtml::encode($data->active); ?>
	<br />


</div>

backend/views/queue/admin.php
<?php
/* @var $this QueueController */
/* @var $model Queue */


$this->breadcrumbs=array(
	'Queues'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Queue', 'url'=>array('index')),
	array('label'=>'Create Queue', 'url'=>array('create')),
);


?>

<h1>Очереди</h1>


<?php $this->widget('PGridView',array(
	'id'=>'queue-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'widgetHeader'=>'',
	'columns'=>array(
		// 'id',
		'name',
		'description',
		'activeProvider.provider.name',
		array(
			'class'=>'PButtonColumn',
		),
	),
)); ?>

backend/views/queue/create.php
<?php
/* @var $this QueueController */
/* @var $model Queue */
?>

<?php
$this->breadcrumbs=array(
	'Queues'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Queue', 'url'=>array('index')),
	array('label'=>'Manage Queue', 'url'=>array('admin')),
);
?>

    <div class="widget row-fluid form-horizontal ">
        <div class="navbar">
            <div class="navbar-inner">
                <h6>Добавление</h6>
            </div>
        </div>
        <?php $this->renderPartial('_form', array('model'=>$model)); ?>    </div>

backend/views/queue/index.php
<?php
/* @var $this QueueController */
/* @var $dataProvider CActiveDataProvider */
?>

<?php
$this->breadcrumbs=array(
	'Queues',
);

$this->menu=array(
	array('label'=>'Create Queue','url'=>array('create')),
	array('label'=>'Manage Queue','url'=>array('admin')),
);
?>

<h1>Queues</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

backend/views/queue/update.php
<?php
/* @var $this QueueController */
/* @var $model Queue */
?>

<?php
$this->breadcrumbs=array(
	'Queues'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Queue', 'url'=>array('index')),
	array('label'=>'Create Queue', 'url'=>array('create')),
	array('label'=>'View Queue', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Queue', 'url'=>array('admin')),
);
?>

    <div class="widget row-fluid form-horizontal ">
        <div class="navbar">
            <div class="navbar-inner">
                <h6>Редактирование</h6>
            </div>
        </div>
        <?php $this->renderPartial('_form', array('model'=>$model)); ?>    </div>

backend/views/queue/view.php
<?php
/* @var $this QueueController */
/* @var $model Queue */
?>

<?php
$this->breadcrumbs=array(
	'Queues'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Queue', 'url'=>array('index')),
	array('label'=>'Create Queue', 'url'=>array('create')),
	array('label'=>'Update Queue', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Queue', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Queue', 'url'=>array('admin')),
);
?>

<h1>View Queue #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView',array(
    'htmlOptions' => array(
        'class' => 'table table-striped table-condensed table-hover',
    ),
    'data'=>$model,
    'attributes'=>array(
		'id',
		'name',
		'description',
		'active',
	),
)); ?>